name: srinivasan
favicon: null
layout_spectrum: 0.3951527043245733
typography_spectrum: 0.6168667320162058
title: "Srinivasan's Personal Blog"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8432406026404351
  lightness: 0.5357274385169148
  saturation: 0.46174782840535045
  rhythmicContrast: 0.6379732687491924
purpose: []
